using System.Text.RegularExpressions;

namespace morse_auth
{
    /// <summary>
    /// The keys for encrypting outcoming data
    /// </summary>
    public static class EncryptionKeys
    {
        /*
         * These keys were generated by
         * https://cryptotools.net/rsagen
         */
        private const string _privateKeyRaw = "-----BEGIN RSA PRIVATE KEY-----\r\nMIIEogIBAAKCAQB30iuu4vA4Hm0lx6dJM5V7cpDY9B7N7ia60ZOhQw9Sqir1eJuP\r\ni/pxD81orEvDi/8Q77JglVM8LJnLUTx4JOhVYi2nFRlEWYUKO+nKzLi7b4P5+xfD\r\nLagj7uW2+E6D2HDeZzOsq2RBuupd3OokABLQVJpG2DPWSCZsnJOrSCVF6Wm3InS3\r\ncKjltlnD70DzLCFwTCRO5WBGlyQ02UsR05i+wPfA+DaIcKCOhGwx+DmywTAGag10\r\nr38skxsYgzrZz5KYxt0zB9L9JiAjHfJ+ZS0FS9v4nUvcQ8pg1PhKRzx62mAeN9yk\r\nEmxeOYWy10uFRYUuMyDpnZbcbnYm5/KbHgQHAgMBAAECggEAUKIgAX342Fspan40\r\nRl+vXbbYYRfPTxfP+nKk3aXqPuADLtPuI6i4bbOLsMAZ8Eta58PWj4aNz/XXvWo6\r\nvkNgEm2SeVkKeuOfUybEi1Q/kOtXrjdaY19rQls3PW1WMQXL1u8uaCmiu1UU+Pt8\r\nmaNvBcGZXMmMAMznBrpL6b0QUD32SdPrDohfQQPyVu0Dgb1sawOB9q58+ApXnAas\r\n9zUolDzVA744wY5eWdlk5nKjmiAWELQ+XNjtPzWbq59uxFYTtB9Cn1su/8E24vMD\r\nTYo65rPcjSwFIPlVWNVPFRpMzGcf7VhCKyFqSuTXvvrj79yEoyQ9ZL0PknOlaC2R\r\nMT/j6QKBgQDU6CX0CNpv+s/OuYVaH6+UIMJJvXDsF6cJjM5azV7x6qSazMN5asix\r\nGxQJHScNxJk3534NQchGzHc42wKdfLb7e9I91t7ksS6Nznhtzt5hrwwZ1rEX7xaG\r\nvS7KtB1GZHzNRBGJDDRGr5UNgcTezzcJv/U9vTLaAFBJ41uLPmEkQwKBgQCQEr3+\r\nYLowV4nFpQRZCG4+JSXhoxep4+N1PCatwlDij7OGXcpKi8qoso3Ib63WuGDdX9sn\r\nzBirQ9RskXQh76VCMlERZLqFBOlsDeCl8tVhT4LkjbXtmpYcWNR1ZgwjShoxJv1m\r\nsx9sVvgWNg9rGVL3uHc+yxgwVVzqY3fTBuSm7QKBgGe2ks53BZmpD1P/scM+TjSV\r\nZK+xNfH8b6VKTzeSdZ7ZE8hI2SwrZYpIy5DI/75IN+8wuInSsrIyZh1vKq33E9gb\r\n8EWphzjWSvxPSQEM1e217OolWG11TX7jZ4jdBqnEx7riXrxpEoogfDZxMarsPD5m\r\noRurL7tcjcAAnhaNk5qrAoGAUnFHI086e/s7rUu2ZzQ50Xn0aV+oZOExAZ8ACyJM\r\norjUZCk7XtkLiOlT1MSDV4F+fG8ju2xBGY/g+JdrOxglGvIsDaX0TbX31ItEZ/HD\r\nRMH5BsxItMRm7aWvPda9T1xSDJphGumZK6fAowUgYYrGPVbjdZ1GJDJUzxNIOAuT\r\nwCkCgYEAnbtSsr274eglY35bQMUlgjJiV8G5hnRy57dzGKCBBDjISoxtWs+uDKDm\r\niuqg43kO6ayVDH7KVY/5sq18riE0azsSiDLnKkcf//PVLPQEsdF8d/p2u5MXbFlf\r\ni8KnpcWaQ4XBYXLpV3t5UBRV/AQ169Cg5Tzn+qFnybF9JUBhamk=\r\n-----END RSA PRIVATE KEY-----";
        private const string _publicKeyRaw = "-----BEGIN PUBLIC KEY-----\r\nMIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQB30iuu4vA4Hm0lx6dJM5V7\r\ncpDY9B7N7ia60ZOhQw9Sqir1eJuPi/pxD81orEvDi/8Q77JglVM8LJnLUTx4JOhV\r\nYi2nFRlEWYUKO+nKzLi7b4P5+xfDLagj7uW2+E6D2HDeZzOsq2RBuupd3OokABLQ\r\nVJpG2DPWSCZsnJOrSCVF6Wm3InS3cKjltlnD70DzLCFwTCRO5WBGlyQ02UsR05i+\r\nwPfA+DaIcKCOhGwx+DmywTAGag10r38skxsYgzrZz5KYxt0zB9L9JiAjHfJ+ZS0F\r\nS9v4nUvcQ8pg1PhKRzx62mAeN9ykEmxeOYWy10uFRYUuMyDpnZbcbnYm5/KbHgQH\r\nAgMBAAE=\r\n-----END PUBLIC KEY-----";
        public static string PrivateKey { get; } = Regex.Unescape(_privateKeyRaw).Trim();
        public static string PublicKey { get; } = Regex.Unescape(_publicKeyRaw).Trim();
    }
}
